create table author (
    id bigint generated by default as identity primary key,
    birth_year integer,
    death_year integer,
    whereabouts varchar,
    photo image
);

create table author_name (
    id bigint generated by default as identity primary key,
    author_id bigint not null references author (id) on delete cascade,
    name varchar not null,
    type varchar not null,
    language varchar not null
);

create index xf_author_name_author on author_name (author_id);
create index x_author_name_name on author_name (name);

create table author_language(
    id bigint generated by default as identity primary key,
    author_id bigint not null references author (id) on delete cascade,
    language varchar not null,
    is_default boolean
);

create index author_language_author on author_language (author_id);